- client/client.go
- client/directory.go
- client/http.go
- client/phonebook.go
- client/workloads.go
- models/generated/workloads/reservation.go
- models/id.go
- pkg/workloads/reservation.go
- pkg/workloads/types/reservation.go
If no available reservations for the node, force it to sync to last poll cursor by sending a NOOP workload
> If no workloads for the node, move to end

- go.sum
- pkg/workloads/reservation.go
- pkg/workloads/types/reservation.go
This to avoid situation when multiple nodes receives same gwid
> Make sure to also use nodeid with gwid to delete

- pkg/directory/types/gateway.go
- pkg/directory/types/node.go
- pkg/workloads/reservation.go
After this change a node marked as free to use means that the node also
accept freeFTF in addition to all the other supported currency of the
farmer.
This change from the current definition which was the node can only be
paid with FreeTFT.
fixes #50
> change definition of freeTFT

- client/workloads.go
- client/workloads_test.go
- go.sum
Skipping unknown workload id when iterating over the list and not returning an error to the caller. This fix the increment issue. On theses logs, we can see next is incremented, one unsupported workload was added.
```
[+] provisiond: 2020-06-02T08:17:28Z info Polling for reservations next=18
[+] provisiond: 2020-06-02T08:17:38Z info Polling for reservations next=18
[+] provisiond: 2020-06-02T08:17:38Z info check for expired reservation
[+] provisiond: 2020-06-02T08:17:48Z info Polling for reservations next=18
[+] provisiond: 2020-06-02T08:17:58Z info Polling for reservations next=19
[+] provisiond: 2020-06-02T08:17:58Z info check for expired reservation
[+] provisiond: 2020-06-02T08:18:08Z info Polling for reservations next=19
[+] provisiond: 2020-06-02T08:18:18Z info Polling for …
```
> Fix unknown workload increment in client

- cmds/tfuser/cmds_network.go
- cmds/tfuser/main.go
- provision/builders/networkBuilder.go
When doing `tfuser network --schema xxx add-node` the schema was not updated at all. First error was a `bad file descriptor` and second error was network resource not present at all on dump.
This pull request fix that, but maybe not the best way expected. Review welcome.
> tfuser: fix network add-node not updating schema with network resources

- provision/builders/networkBuilder.go
this is to avoid the network generation to use yggdrasil IP address as
public endpoint
> add yggdrasill range in the list of private network

- cmds/tfuser/cmds_container.go
- cmds/tfuser/main.go
Recent changes prevent container to be executed on HDD, only SSD are
allowed as disk-type. Disable user selection and force disk to be set as
SSD by default.
> Disable disk-type selection on tfuser

- pkg/capacity/conversion.go
- pkg/capacity/conversion_test.go
Compute cloud units as described on
https://wiki.threefold.io/#/cloud_units. There is also another
computation for cloud units in the code, which uses a legacy formula.
This code path is however no longer used and will be removed in a future
cleanup, most likely as part of #121
> Fix #132: Ensure right cloud formula is used

- models/generated/workloads/workload.go
- pkg/workloads/reservation.go
- pkg/workloads/reservation_test.go
- pkg/workloads/types/pipeline.go
- pkg/workloads/types/reservation.go
- pkg/workloads/types/signature.go
- pkg/workloads/types/signature_test.go
- pkg/workloads/types/workload.go
- pkg/workloads/types/workloadpipeline.go
After this commit, user that are requested in the delete or provision
consensus are only able to push a signature once.
If they already have a signature registered and try to put a new one, an
400 bad request error will be returned by the API.
This change allow to simplify the way we deal with signature array
internally and should prevent issue like #141
fixes #141
> change how delete and provision signature are accepted and verified

- pkg/workloads/reservation.go
so we avoid them to be picked up by provisiond on next restart.
fixes #144
> mark workload that are not allow to be deployed as invalid

- frontend/src/views/capacity/capacity.html
people seems to be confused by this number and it doesn't really bring
any useful information, so we just keep the online nodes and gateways
instead.
> remove panel for total number of nodes and gateways

- pkg/capacity/planner.go
- pkg/escrow/stellar.go
- pkg/workloads/reservation.go
Specifically, allow a new pool reservation to modify an existing pool by only
adding new node ids. In such a scenario, an escrow would previously be
set up for 0 value, which would cause errors on the payouts. Now detect
this specific scenario, and in the escrow stage, immediatly mark the
reservation as paid, without checking for an actual payment. This way we
still have the reservation in DB for the blockchain behavior.
Also, actually allow adding new nodes to an existing pool (previously
all checks were done but the update itself did not happen), and detect
if a reservation will have no observeable effect (i.e. no added CU,SU,or
nodes). In case of the latter, reject the reservation.
> Fix #162: Allow extending pools without CU or SU

- client/filter.go
- models/generated/directory/directory.go
- pkg/directory/node_handlers.go
- pkg/directory/nodes_store.go
- pkg/directory/types/node.go
- pkg/workloads/conversion.go
- pkg/workloads/reservation.go
From now on, set a tombstone marker on nodes which are deleted. A new
filter is added when listing nodes, to also show deleted nodes (which is
not done by default). Updates to nodes marked as deleted are also
prohibited (the node will not be found). However, to maintain old
behavior, the NodeCreate call _is_ allowed (and will now clear the
tombtone if present). Looking up  a specific node will always succeed.
Fix #164
> Mark nodes as deleted instead of actually deleting

- cmds/tfuser/cmds_container.go
- go.mod
- models/generated/workloads/container.go
- models/generated/workloads/workload.go
- provision/builders/containerBuilder.go
There is a `StatsAggregator` generic defined on original spec, and the same name was used to defines *Container Statistics*, but container statistics are not generic and are specific to containers only.
This change rename `StatsAggregator` type and field name for container, to switch to just `Stats`.
> Rename StatsAggregator to Stats for Container

- pkg/capacity/planner.go
- pkg/capacity/planner_test.go
When a pool expires, only delete the workloads which are consuming
resources of which there are non left in the pool. This means that pools
running out of CU won't have their volumes deleted, since those only
consume SU, for example. This also means that network related workloads
will never be deleted, since we don't have NU right now, so they do not
consume any resources at all.
Signed-off-by: Lee Smet <lee.smet@hotmail.com>
> Close #171: only delete out of resource workloads

- client/http.go
This is will be used later to decide if we should
retry to do the request or the error is permanent
> Add solid error type so client can check

- Makefile
- models/generated/workloads/container.go
- models/generated/workloads/network.go
- models/generated/workloads/network_resource.go
- models/generated/workloads/workload.go
- models/generated/workloads/zdb.go
Multiple time `SigingEncode` was used in place of `SigningEncode`
This fix `gocyclo` install aswell, like in: https://github.com/threefoldtech/zos/commit/cc8838abef4900e02856e9ce3560b9bab8879c05
> Update 'Siging' to 'Signing' typo

- pkg/workloads/reservation.go
Fixes #225
So in this fix we should only return "queued" workloads only if there are nothing to return from the reservations query. The queue is only to process older reservations that are suddenly available for processing (for example expired reservations)
But now many reservations are ready from the beginning if the pool has capacity, so we store the reservation in both the reservation collections, and also we push it to the queue. 
This will make the node get the reservations 2 times since the workloads endpoint will query matching reservations, and also the queue. then the node will receive the same reservation 2 times.
instead we only check the queue if no other reservations available
> make sure that we send queue only if no more workloads to process

- pkg/directory/gateway_handlers.go
- pkg/directory/setup.go
- Make sure that the gateway registration actually validate that the gateway node id is owned by the requester by validating it against the httpsig key.
- Validate managed domains that they are actually managed by that gateway by validating the TXT record of `__owner__.<domain>` that it has the right identity. (requires https://github.com/threefoldtech/tfgateway/pull/55)
> make sure to validate gw register request

- pkg/capacity/planner.go
This will make expired pools gets checked more often
if something goes wrong
> shorter fall safe check for pool expirey

- cmds/tffarmer/farm.go
- go.sum
- migrations/wallet_address/main.go
- models/generated/directory/directory.go
- mw/action.go
- pkg/capacity/planner.go
- pkg/capacity/types/pool.go
- pkg/capacity/types/reservation.go
- pkg/directory/farms_handlers.go
- pkg/directory/farms_store.go
- pkg/directory/node_handlers.go
- pkg/directory/setup.go
- pkg/directory/types/farm.go
- pkg/directory/types/farmthreebotprice.go
- pkg/directory/types/setup.go
- pkg/escrow/resource.go
- pkg/escrow/stellar.go
- pkg/workloads/conversion.go
- pkg/workloads/reservation.go
This PR should fix #277 
- updating the generated/directory models with NodeCloudUnitPrice 
- set default pricing on the farm as option (defaults to zero value to allow falling back to explorer pricing)
- define type FarmThreebotPrice and model interaction list, find, filters
- Adds deals endpoints (get/create/update/delete)
- Adds sponsorTid, sponsorSignature to be able to apply deals when processing capacity reservation
also fixes #287
> Farm custom pricing

- models/generated/directory/directory.go
- models/generated/workloads/reservation.go
- pkg/directory/farms_handlers.go
- pkg/directory/node_handlers.go
- pkg/directory/setup.go
- pkg/directory/types/node.go
- pkg/workloads/reservation.go
This PR implements the actual operation once the node is reserved. It will allow only workloads from that user to be deployed on this node. The PR though does not implement ways to reserve a node, nor the billing part.
We need input on:
- Who is gonna set this flag? the farmer? 
- Once the node is reserved, how this gonna affect billing. Should the user still be billed for only the deployed workloads (the way we do now) or other changes is needed.
-
> feat: add field that dedicates a node to a certain user

- cmds/tfexplorer/main.go
- pkg/escrow/escrow.go
- pkg/escrow/stellar.go
- pkg/escrow/types/escrow.go
- pkg/escrow/types/failed.go
- pkg/escrow/types/memos.go
- pkg/escrow/types/setup.go
- pkg/stellar/retry.go
- pkg/stellar/stellar.go
1. Make all payments and refunds go through the paymentsChannel and aggregate them until nothing comes in, the number of payments exceeds 80% of stellar limit, (100) or the number of signatures exceeds the limit 20 - 1 (the funding wallet signature).
2. FarmerPayouts are retried 2 times, in case of failure, it gets pushed back to the tail of the queue.
3. In case a farmer payout fails, a client refund is issued to the client with retries = 6, in case this fails it gets stored in the db.
4. In case the transaction failed, the successful payouts are repushed (they doesn't take effect since the whole tx failed), the failed ones decreases the retries and gets pushed back.
5. Since paying farmers are bundled, they doesn't contain memo text. This is fixed by storing in mongo the mapping from …
> Payment aggregation
