pkg/phonebook/types/user.go
pkg/phonebook/types/user_test.go
pkg/phonebook/user.go
pkg/phonebook/user_test.go
pkg/stellar/stellar.go

copied from https://github.com/threefoldtech/zos/commit/06295a04868fae415c847d48c351bd3bb07f0360

Validate email is lowercase improve status code return by update user

---

frontend/src/App.vue
frontend/src/store/transaction.js
frontend/src/views/capacity/capacity.js

Adds automatic and manual refresh

---

pkg/escrow/resource.go
pkg/escrow/resource_test.go
pkg/workloads/reservation.go

Update cloud unit pricing

---

frontend/src/components/gatewayinfo/gatewayinfo.html
frontend/src/components/gatewaystable/gatewaystable.html

fix some bugs in frontend gateways

---

pkg/escrow/stellar.go
pkg/workloads/types/reservation.go

After reservation is paied, it must be pushed to queue
not only marked with next_action

Make sure we push reservation to workload

---

pkg/escrow/resource.go
pkg/escrow/resource_test.go
pkg/workloads/reservation.go

based on https://docs.google.com/spreadsheets/d/1z8-TRdpSCOa_BNPFTvu--IQ6z1FEQGBElgTGcf57n_E/edit#gid=0

Update pricing model

---

models/generated/workloads/reservation.go

Fix index names

---

cmds/tfuser/cmds_container.go
cmds/tfuser/main.go
models/generated/workloads/container.go
models/schema/workloads/tfgrid_workloads_reservation_container_1.toml
pkg/escrow/resource.go

part of https://github.com/threefoldtech/zos/issues/793

allow to configure the size and disk type of containers

---

pkg/stellar/stellar.go

Set the missing tx BaseFee.
Bug introduced in #85

Fix activation of escrow accounts

---

pkg/directory/farms_handlers.go
pkg/directory/nodes_store.go
pkg/directory/setup.go

add deletion of a node belonging to a farm

---

pkg/directory/farms_handlers.go
pkg/directory/farms_store.go
pkg/directory/setup.go
pkg/directory/types/farm.go
pkg/phonebook/setup.go
pkg/phonebook/user.go

don't show email address by default in explorer API

---

frontend/src/components/nodeinfo/nodeinfo.js

show unavailable capacity as grey in frontend

---

migrations/remove_signature/main.go
models/generated/phonebook/phonebook.go

don't return signature field in user listing

---

cmds/tfuser/main.go

tfuser always create a bcdb client

---

pkg/workloads/types/reservation.go

Related: https://github.com/threefoldtech/zos/issues/832

validate zdb, container and volume disk types

---

pkg/escrow/stellar.go

The current flow tries to pay the farmer if the capacity reservation has
been paid. If this fails however, we now try to refund the user.
Fixes #135

Refund capacity escrows if farmer payout fails

---

pkg/workloads/reservation.go

also take in account the gateways when checking for free to use node during pool creation

---

models/generated/workloads/container.go

part of https://github.com/threefoldtech/zos/issues/868

add field to container workload to allocate yggdrasil IP

---

models/generated/workloads/workload.go
pkg/workloads/reservation.go

relates to https://github.com/threefoldtech/zos/pull/993

add version field to the workload object

---

pkg/phonebook/types/user.go

phonebook: do not allow user to update its public key

---

pkg/workloads/reservation.go
pkg/workloads/setup.go

Testing is needed, hence i am still working on the sdk side to provide the proper headers.
Fixes #192

authentication for create requests

---

models/generated/workloads/k8s.go

add new sizes for k8s VM workload

---

go.mod
go.sum
pkg/stellar/stellar.go

Not sure if we should keep trying for ever or timeout after a while? @zaibon your thoughts?

Add backoff for account creation

---

pkg/escrow/resource.go

Update pricing based on #215

---

pkg/workloads/reservation.go

Only return the global LastID if not other reservations are
available for this node id

the last id need to be the last id in the list

---

pkg/capacity/conversion.go
pkg/capacity/conversion_test.go
pkg/capacity/planner.go
pkg/capacity/types/pool.go

Aligns cloud units calculation to the one used in the JS-SDK 
https://github.com/threefoldtech/js-sdk/blob/11be30cd6a64aea243fa0ce0dd4efb8191c6c98f/jumpscale/clients/explorer/models.py#L128

wip: fix cloud units calculation

---

pkg/capacity/planner.go

Fix pool capacity on boot

---

models/generated/workloads/public_ip.go
pkg/directory/types/farm.go
pkg/workloads/reservation.go
pkg/workloads/types/setup.go
pkg/workloads/types/workload.go

https://github.com/threefoldtech/zos/issues/1097
https://github.com/threefoldtech/zos/issues/1099

Adds checks when a public ip is referenced in a kubernetes reservation

---

pkg/escrow/resource.go
pkg/escrow/stellar.go

Add logic to calculate ipv4 prices

---

go.mod
go.sum
pkg/directory/gateway_handlers.go
pkg/directory/types/gateway.go

also validate domain names
Relates to #249

validate gateway registration

---

pkg/escrow/resource.go

Fixes https://github.com/threefoldtech/tfexplorer/issues/260

adjust price to 0.1 usd

---

frontend/public/docs/api_v1.json
pkg/escrow/stellar.go
pkg/escrow/types/escrow.go
pkg/workloads/reservation.go
pkg/workloads/setup.go

We also introduce a new API to return payment information to caller where they can check the status and the cancellation cause.

make sure to store cause of cancellation on payment info

---

cmds/stellar/multisig.go
pkg/escrow/resource_test.go
pkg/escrow/stellar.go
pkg/stellar/crypto.go
pkg/stellar/retry.go
pkg/stellar/stellar.go

The idea is we retry on failed operation that is caused by out of sync sequence number
Related to #233 and #159

A retry wrapper to retry failed operations

---

pkg/directory/gateway_handlers.go
pkg/directory/node_handlers.go
pkg/directory/types/gateway.go

Fixes https://github.com/threefoldtech/tfgateway/issues/57
This PR validate that the given value for farm-id is a valid value. It does not validate that this node is actually owned by this farm.

wip: validate id

---

pkg/workloads/reservation.go

Related: https://github.com/threefoldtech/zos/issues/1152

return not found when error is mongo no doc error

---

models/generated/workloads/k8s.go

Signed-off-by: Lee Smet <lee.smet@hotmail.com>

Add extra options for k8s workload

---

pkg/directory/farms_handlers.go
pkg/directory/setup.go

fixes delete method usage with deals endpoint

Update deals delete method

---

pkg/escrow/escrow.go
pkg/escrow/resource_test.go
pkg/escrow/stellar.go
pkg/escrow/types/escrow.go
pkg/workloads/reservation.go

Related to #121
Signed-off-by: Lee Smet <lee.smet@hotmail.com>

Cleanup legacy escrow code

---

models/generated/directory/directory.go
models/generated/phonebook/phonebook.go
pkg/directory/types/farm.go
pkg/escrow/payout_distribution.go
pkg/escrow/payout_distribution_test.go
pkg/escrow/resource.go
pkg/escrow/stellar.go
pkg/escrow/stellar_test.go
pkg/workloads/reservation.go

This implements this issue
https://github.com/threefoldtech/home/issues/1041

V3 pricing

---

frontend/src/App.vue

For https://github.com/threefoldtech/tfexplorer/issues/345

Add migration from v2 to v3 message
